# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lA3ulvMPeF4rla0HkyC4b03Rl72s5Txi
"""

import pandas as pd

airplane = pd.read_csv('/content/drive/MyDrive/codeveda technology/level 1/Airplane_Crashes_and_Fatalities_Since_1908.csv')
airplane.head(10)

airplane.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.lineplot(data=airplane,x='Location',y='Type',marker='o',color='green',label='Location with flight type')
plt.title('Location with flight type')
plt.xlabel('Location')
plt.ylabel('Flight Type')
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
top_10_location = airplane['Location'].value_counts().nlargest(10).index
top_10_flightstype = airplane['Type'].value_counts().nlargest(10).index

airplane_top_10_flight_location = airplane[
    airplane['Location'].isin(top_10_location)&
    airplane['Type'].isin(top_10_flightstype)
]

plt.figure(figsize=(10,6))
sns.lineplot(data = airplane_top_10_flight_location,x='Location',y='Type',marker='o',color='green',label='Location with flight type')
plt.title('Location with flight type')
plt.xlabel('Location')
plt.ylabel('Flight Type')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))


airplane_cleaned = airplane.dropna(subset=['Route'])


top_10_routes = airplane_cleaned['Route'].value_counts().nlargest(10)


plt.bar(top_10_routes.index, top_10_routes.values, color='red', label='Top 10 Routes')
plt.title('Top 10 Most Frequent Routes')
plt.xlabel('Route')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout() g
plt.show()