# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17L7nrB6B59l7Vt9qudVNuM1eLNvP76YA
"""

import pandas as pd

missing = pd.read_csv("/content/drive/MyDrive/codeveda technology/level 1/Diabetes Missing Data.csv")
missing.head(10)

missing.isnull().sum()

missing.describe()

missing.info()

missing['BMI'] = missing['BMI'].fillna(missing['BMI'].mean())
missing['Serum_Insulin'] = missing['Serum_Insulin'].fillna(missing['Serum_Insulin'].mode()[0])

missing['Skin_Fold'] = missing['Skin_Fold'].fillna(missing['Skin_Fold'].median())

missing.isnull().sum()

missing['Diastolic_BP'] = missing['Diastolic_BP'].fillna(missing['Diastolic_BP'].mean())

missing.isnull().sum()

missing['Diabetes_Pedigree'].dropna()

missing_cleanes = missing.dropna()

missing_cleanes.isnull().sum()